/gate/source/addSource point_source_offset_5
# The total activity of the source is set
#/gate/source/point_source_offset_5/setActivity 0.0000001 Ci
/gate/source/point_source_offset_5/setActivity 1000000 Bq
# The source emits pairs of particles back-to-back
/gate/source/point_source_offset_5/setType backtoback
# The particles emitted by the source are gammas
/gate/source/point_source_offset_5/gps/particle gamma
# The gammas have an energy of 511 keV
/gate/source/point_source_offset_5/gps/energytype Mono
/gate/source/point_source_offset_5/gps/monoenergy 0.511 MeV
# The source is a full sphere with radius 0.1 mm,
# located at the centre of the FOV
/gate/source/point_source_offset_5/gps/type Volume
/gate/source/point_source_offset_5/gps/shape Sphere
/gate/source/point_source_offset_5/gps/radius 0.1 mm
/gate/source/point_source_offset_5/gps/centre 5. 0. 0. cm
# The angular distribution of emission angles is isotropic
/gate/source/point_source_offset_5/gps/angtype iso

# The parameters below mean that the source emits
# at all angles along the z axis
#/gate/source/point_source_offset_5/gps/mintheta 0. deg
#/gate/source/point_source_offset_5/gps/maxtheta 180. deg
# Uncomment the parameters below if you want the source
# to emit in an XY (transverse) plane
#/gate/source/point_source_offset_5/gps/mintheta 90. deg
#/gate/source/point_source_offset_5/gps/maxtheta 90. deg
# The parameters below mean that the source emits
# at all angles in the transverse (XY) directions
#/gate/source/point_source_offset_5/gps/minphi 0. deg
#/gate/source/point_source_offset_5/gps/maxphi 360. deg


/gate/source/point_source_offset_5/visualize 2000 green 3
/gate/source/list


/gate/source/addSource point_source_center
# The total activity of the source is set
#/gate/source/point_source_center/setActivity 0.0000001 Ci
/gate/source/point_source_center/setActivity 1000000 Bq
# The source emits pairs of particles back-to-back
/gate/source/point_source_center/setType backtoback
# The particles emitted by the source are gammas
/gate/source/point_source_center/gps/particle gamma
# The gammas have an energy of 511 keV
/gate/source/point_source_center/gps/energytype Mono
/gate/source/point_source_center/gps/monoenergy 0.511 MeV
# The source is a full sphere with radius 0.1 mm,
# located at the centre of the FOV
/gate/source/point_source_center/gps/type Volume
/gate/source/point_source_center/gps/shape Sphere
/gate/source/point_source_center/gps/radius 0.1 mm
/gate/source/point_source_center/gps/centre 0. 0. 0. cm
# The angular distribution of emission angles is isotropic
/gate/source/point_source_center/gps/angtype iso



/gate/source/point_source_center/visualize 2000 red 3
/gate/source/list
